binary_sensor:      
  - platform: template
    sensors:
      pralka:
        friendly_name: "Pralka"
        value_template: "{{ states('sensor.pralka_energy_power')|float > 2.0 }}" 
           
