binary_sensor:

  - platform: burze_dzis_net
    api_key: 592027ae1bb562c0a1f1a727f8d1eb713bfee687
    warnings:
      - frost_warning
      - heat_warning
      - wind_warning
      - precipitation_warning
      - storm_warning
      - tornado_warning
    storms_nearby:
      radius: 30
      
  - platform: template
    sensors:
      pralka:
        friendly_name: "Pralka"
        value_template: "{{ states('sensor.pralka_energy_power')|float > 2.0 }}" 
           